# This code is licensed from CircleCI to the user under the MIT license. See
# https://circleci.com/orbs/registry/licensing for details.
version: 2.1
description: |
  Run Flay on your ruby code in an orb 🔮
  Contribute at: https://github.com/HParker/flay-orb

commands:
  install-flay:
    description: Install Flay
    parameters:
      version:
        default: ""
        description: Flay gem version
        type: string
    steps:
    - run:
        command: |
          if [ -z "<< parameters.version >>" ]; then
            gem install flay
          else
            gem install flay --version "<< parameters.version >>"
          fi
        name: Install Flay << parameters.version >>
  run-flay:
    description: Run Flay
    parameters:
      options:
        default: ""
        description: CLI options
        type: string
    steps:
    - run: flay << parameters.options >>

examples:
  flay:
    description: |
      Run Flay
    usage:
      orbs:
        flay: hparker/flay@x.y.z
      version: 2.1
      workflows:
        test:
          jobs:
          - flay/flay
        version: 2
  flay-version:
    description: |
      Run specific version of Flay
    usage:
      orbs:
        flay: hparker/flay@x.y.z
      version: 2.1
      workflows:
        test:
          jobs:
          - flay/flay:
              version: 2.12.1
        version: 2

executors:
  ruby:
    docker:
    - image: rubylang/ruby:latest
jobs:
  flay:
    description: Checkout code and run Flay
    executor: << parameters.executor >>
    parameters:
      executor:
        default: ruby
        description: executor for flay
        type: executor
      options:
        default: ""
        description: CLI options
        type: string
      version:
        default: ""
        description: Flay version
        type: string
    steps:
    - checkout
    - install-flay:
        version: << parameters.version >>
    - run-flay:
        options: << parameters.options >>
